version: '3'

services:
  app:
    build: .
    entrypoint: wait-for mysql:3306 -t 40 -- sh -c 'npm install && npm run start:dev'
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "docker.for.mac.host.internal:172.17.0.1"
  
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    extra_hosts:
      - "docker.for.mac.host.internal:172.17.0.1"

volumes:
  mysql:
    driver: local